### PR TITLE
Use defer to close http response body in auto generated client code

### PR DESCRIPTION
**Pull request by donutloop**
Less Code Less Complexity Less time to worry 

Replaced all` response.Body.Close` calls inside of each Client handler with a deferred `response.body.Close`. The autogenerated code is less complex and the client generator is better adaptable in case of adding new response cases or adapting the current set of response cases. Reduces the likelihood of introducing a memory leak to an optiminun

### CODE REVIEW

**Comment by donutloop** [comment]
@seseloos please have a look!

**Comment by donutloop** [comment]
@seseloos I resolved all merge conflicts

**Comment by seseloos** [comment]
@donutloop I will review the changes in the next days and give you feedback on the request.

**Comment by donutloop** [comment]
@seseloos Sounds good to me!

**Review by seseloos — APPROVED** [review]

**Pull request merged**
