### PR TITLE
ACG: Decompose client interface

### PR DESCRIPTION
**Pull request by donutloop**
* Decompose client interface into smaller interfaces, fewer methods need to be satisfied.
* Can be used to make code more lean and clean, reader knows exactly which method are needed from the client.
* Allows fine granular definition of new interface types

### CODE REVIEW

**Comment by donutloop** [comment]
i still need to update the readme

**Comment by donutloop** [comment]
@seseloos ready for review

**Comment by donutloop** [comment]
@seseloos ?

**Review by seseloos — APPROVED** [review]
LGTM

**Pull request merged**
